package mvc

import (
	"fmt"
	"net/http"
	"path/filepath"
	"reflect"
	"runtime"
	"strings"

	requestcontext "github.com/jcdomt/yuhuo/context"
	route "github.com/jcdomt/yuhuo/router"
)

// ControllerRouteGroup 描述 MVC 注册路由所需的最小能力
type ControllerRouteGroup interface {
	HandleWithSource(method, pattern string, handler requestcontext.HandlerFunc, source string, middlewares ...requestcontext.HandlerFunc)
}

// BaseController 为控制器提供当前请求上下文的约定字段
type BaseController struct {
	Ctx *requestcontext.Context
}

// ControllerRouter 是控制器声明路由时使用的受限接口
type ControllerRouter struct {
	group         ControllerRouteGroup
	prefix        string
	newController func() reflect.Value
}

// Handle	按 HTTP 方法注册控制器路由，日志中附带处理器方法的定义位置
//
// param:
//   - method	HTTP 方法
//   - path	路由路径
//   - handler	控制器处理函数
//   - middlewares	路由中间件列表
func (router ControllerRouter) Handle(method, path string, handler requestcontext.ControllerFunc, middlewares ...requestcontext.HandlerFunc) {
	if router.group == nil {
		panic("yuhuo/mvc: controller router is not initialized")
	}

	fullPath := joinControllerPath(router.prefix, path)
	router.group.HandleWithSource(method, fullPath, controllerFuncToHandlerFunc(handler, router.newController), controllerFuncSource(handler, router.newController), middlewares...)
}

// controllerFuncSource	解析控制器函数（具名方法或匿名函数）的定义位置
// 具名方法会绑定生成 <autogenerated> 包装桩，需通过控制器类型反查真实定义处
//
// param:
//   - handler	控制器处理函数
//   - newController	控制器工厂函数
// return:
//   - 定义位置，无法解析时返回空字符串
func controllerFuncSource(handler requestcontext.ControllerFunc, newController func() reflect.Value) string {
	methodName, isControllerMethod := controllerMethodName(handler)
	if isControllerMethod && newController != nil {
		if source := controllerMethodSource(newController, methodName); source != "" {
			return source
		}
	}

	source := route.HandlerSource(handler)
	if strings.HasPrefix(source, "<autogenerated>") {
		return ""
	}
	return source
}

// controllerMethodSource	通过控制器类型的方法表解析具名方法的定义位置
// 值接收者方法经指针类型查找会得到 <autogenerated> 包装桩，因此优先在元素类型上解析
//
// param:
//   - newController	控制器工厂函数
//   - methodName	方法名
// return:
//   - 方法定义位置，无法解析时返回空字符串
func controllerMethodSource(newController func() reflect.Value, methodName string) string {
	controller := newController()
	if !controller.IsValid() {
		return ""
	}

	controllerType := controller.Type()
	if controllerType.Kind() == reflect.Ptr {
		if source := methodSourceOnType(controllerType.Elem(), methodName); source != "" {
			return source
		}
	}
	return methodSourceOnType(controllerType, methodName)
}

// methodSourceOnType	在指定类型的方法表中查找具名方法并返回其定义位置
//
// param:
//   - controllerType	控制器类型
//   - methodName	方法名
// return:
//   - 方法定义位置，无法解析时返回空字符串
func methodSourceOnType(controllerType reflect.Type, methodName string) string {
	method, found := controllerType.MethodByName(methodName)
	if !found {
		return ""
	}

	function := runtime.FuncForPC(method.Func.Pointer())
	if function == nil {
		return ""
	}

	file, line := function.FileLine(method.Func.Pointer())
	if file == "<autogenerated>" {
		return ""
	}
	return fmt.Sprintf("%s:%d", filepath.ToSlash(file), line)
}

// Group	创建一个新的路由组，并在该组中注册控制器路由
//
// param:
//   - path	子路由组路径前缀
//   - fn	在子路由组中注册路由的回调
func (router ControllerRouter) Group(path string, fn func(r ControllerRouter)) {
	if router.group == nil {
		panic("yuhuo/mvc: controller router is not initialized")
	}
	if fn == nil {
		panic("yuhuo/mvc: controller group callback must not be nil")
	}
	fn(ControllerRouter{group: router.group, prefix: joinControllerPath(router.prefix, path), newController: router.newController})
}

// joinControllerPath	合并控制器路由前缀和相对路径
//
// param:
//   - prefix	路由前缀
//   - path	相对路径
// return:
//   - 合并后的完整路径
func joinControllerPath(prefix, path string) string {
	if path == "" || path == "/" {
		if prefix == "" {
			return "/"
		}
		return prefix
	}
	if !strings.HasPrefix(path, "/") {
		panic("yuhuo/mvc: controller route must begin with '/'")
	}
	if prefix == "" {
		return path
	}
	return strings.TrimSuffix(prefix, "/") + path
}

// controllerFuncToHandlerFunc	将控制器方法转换为请求处理函数
// 具名控制器方法会在每次请求时创建独立实例并注入 Context，匿名函数则保持直接调用
//
// param:
//   - handler	控制器处理函数
//   - newController	控制器工厂函数
// return:
//   - 请求处理函数
func controllerFuncToHandlerFunc(handler requestcontext.ControllerFunc, newController func() reflect.Value) requestcontext.HandlerFunc {
	if handler == nil {
		panic("yuhuo/mvc: controller function must not be nil")
	}

	methodName, isControllerMethod := controllerMethodName(handler)
	if !isControllerMethod || newController == nil {
		return func(ctx *requestcontext.Context) {
			ctx.JSON(handler())
		}
	}

	return func(ctx *requestcontext.Context) {
		controller := newController()
		injectControllerContext(controller, ctx)

		method := controller.MethodByName(methodName)
		if !method.IsValid() {
			panic("yuhuo/mvc: controller method not found: " + methodName)
		}

		results := method.Call(nil)
		if len(results) != 1 {
			panic("yuhuo/mvc: controller method must return exactly one value: " + methodName)
		}

		// 判断函数返回值是否是 mvc.Result 类型，如果是则调用其 Execute 方法，否则直接返回 JSON
		if result, ok := results[0].Interface().(Result); ok {
			result.Execute(ctx)
			return
		}

		ctx.JSON(results[0].Interface())
	}
}

// controllerMethodName	从方法值中提取控制器方法名称
// Go 为方法值生成的运行时名称会以 "-fm" 结尾，匿名函数不具备此特征
//
// param:
//   - handler	控制器处理函数
// return:
//   - 方法名及是否为具名控制器方法
func controllerMethodName(handler requestcontext.ControllerFunc) (string, bool) {
	function := runtime.FuncForPC(reflect.ValueOf(handler).Pointer())
	if function == nil {
		return "", false
	}
	name := function.Name()
	if !strings.HasSuffix(name, "-fm") {
		return "", false
	}

	methodName := strings.TrimSuffix(name[strings.LastIndex(name, ".")+1:], "-fm")
	return methodName, methodName != ""
}

// injectControllerContext	将当前请求上下文注入控制器嵌入的 BaseController
//
// param:
//   - controller	控制器实例
//   - ctx	请求上下文
func injectControllerContext(controller reflect.Value, ctx *requestcontext.Context) {
	if controller.Kind() != reflect.Ptr || controller.IsNil() {
		return
	}
	setBaseControllerContext(controller.Elem(), ctx)
}

// setBaseControllerContext	遍历匿名嵌入字段，支持多层嵌入 BaseController
//
// param:
//   - value	控制器结构体反射值
//   - ctx	请求上下文
// return:
//   - 是否成功注入
func setBaseControllerContext(value reflect.Value, ctx *requestcontext.Context) bool {
	if value.Kind() != reflect.Struct {
		return false
	}

	baseControllerType := reflect.TypeOf(BaseController{})
	for index := 0; index < value.NumField(); index++ {
		field := value.Field(index)
		fieldType := value.Type().Field(index)
		if fieldType.Type == baseControllerType && field.CanSet() {
			field.FieldByName("Ctx").Set(reflect.ValueOf(ctx))
			return true
		}
		if !fieldType.Anonymous {
			continue
		}
		if field.Kind() == reflect.Ptr {
			if field.Type().Elem().Kind() != reflect.Struct || !field.CanSet() {
				continue
			}
			if field.IsNil() {
				field.Set(reflect.New(field.Type().Elem()))
			}
			field = field.Elem()
		}
		if setBaseControllerContext(field, ctx) {
			return true
		}
	}
	return false
}

// GET	注册 GET 路由
//
// param:
//   - path	路由路径
//   - handler	控制器处理函数
//   - middlewares	路由中间件列表
func (router ControllerRouter) GET(path string, handler requestcontext.ControllerFunc, middlewares ...requestcontext.HandlerFunc) {
	router.Handle(http.MethodGet, path, handler, middlewares...)
}

// POST	注册 POST 路由
//
// param:
//   - path	路由路径
//   - handler	控制器处理函数
//   - middlewares	路由中间件列表
func (router ControllerRouter) POST(path string, handler requestcontext.ControllerFunc, middlewares ...requestcontext.HandlerFunc) {
	router.Handle(http.MethodPost, path, handler, middlewares...)
}

// PUT	注册 PUT 路由
//
// param:
//   - path	路由路径
//   - handler	控制器处理函数
//   - middlewares	路由中间件列表
func (router ControllerRouter) PUT(path string, handler requestcontext.ControllerFunc, middlewares ...requestcontext.HandlerFunc) {
	router.Handle(http.MethodPut, path, handler, middlewares...)
}

// DELETE	注册 DELETE 路由
//
// param:
//   - path	路由路径
//   - handler	控制器处理函数
//   - middlewares	路由中间件列表
func (router ControllerRouter) DELETE(path string, handler requestcontext.ControllerFunc, middlewares ...requestcontext.HandlerFunc) {
	router.Handle(http.MethodDelete, path, handler, middlewares...)
}

// PATCH	注册 PATCH 路由
//
// param:
//   - path	路由路径
//   - handler	控制器处理函数
//   - middlewares	路由中间件列表
func (router ControllerRouter) PATCH(path string, handler requestcontext.ControllerFunc, middlewares ...requestcontext.HandlerFunc) {
	router.Handle(http.MethodPatch, path, handler, middlewares...)
}

// HEAD	注册 HEAD 路由
//
// param:
//   - path	路由路径
//   - handler	控制器处理函数
//   - middlewares	路由中间件列表
func (router ControllerRouter) HEAD(path string, handler requestcontext.ControllerFunc, middlewares ...requestcontext.HandlerFunc) {
	router.Handle(http.MethodHead, path, handler, middlewares...)
}

// OPTIONS	注册 OPTIONS 路由
//
// param:
//   - path	路由路径
//   - handler	控制器处理函数
//   - middlewares	路由中间件列表
func (router ControllerRouter) OPTIONS(path string, handler requestcontext.ControllerFunc, middlewares ...requestcontext.HandlerFunc) {
	router.Handle(http.MethodOptions, path, handler, middlewares...)
}
