// 控制器函数参数名解析
// Go 反射无法获取函数参数名，这里通过 go/ast 在注册时解析 handler 的源码文件来提取参数名，
// 使路径参数可以按参数名注入；源码不可用（如部署环境不带 .go 文件）时返回 nil，退化为按顺序注入
package mvc

import (
	"go/ast"
	"go/parser"
	"go/token"
	"reflect"
	"runtime"
	"strconv"
	"strings"

	requestcontext "github.com/jcdomt/yuhuo/context"
	route "github.com/jcdomt/yuhuo/router"
)

// controllerParamNames	解析控制器函数的参数名列表
// 具名控制器方法通过控制器类型反查方法真实定义处（避开 <autogenerated> 包装桩），
// 其余 handler 通过自身的定义位置解析；参数名数量与签名不一致时返回 nil
//
// param:
//   - handler	控制器处理函数
//   - newController	控制器工厂函数
//   - numIn	函数输入参数数量
//
// return:
//   - 参数名列表，无法解析时返回 nil
func controllerParamNames(handler requestcontext.ControllerFunc, newController func() reflect.Value, numIn int) []string {
	if numIn == 0 {
		return nil
	}

	lookupName, isMethod := controllerMethodName(handler)
	if !isMethod {
		lookupName = handlerFuncName(handler)
	}

	// 具名控制器方法优先在方法真实定义处解析
	if isMethod && newController != nil {
		if file, line := splitSourceLine(controllerMethodSource(newController, lookupName)); file != "" {
			if names := functionParamNames(file, line, lookupName); len(names) == numIn {
				return names
			}
		}
	}

	if file, line := splitSourceLine(route.HandlerSource(handler)); file != "" {
		if names := functionParamNames(file, line, lookupName); len(names) == numIn {
			return names
		}
	}
	return nil
}

// handlerFuncName	提取 handler 运行时的基础函数名，匿名函数为 funcN
//
// param:
//   - handler	控制器处理函数
//
// return:
//   - 基础函数名
func handlerFuncName(handler requestcontext.ControllerFunc) string {
	fn := runtime.FuncForPC(reflect.ValueOf(handler).Pointer())
	if fn == nil {
		return ""
	}
	name := fn.Name()
	return name[strings.LastIndex(name, ".")+1:]
}

// splitSourceLine	拆分 "file:line" 形式的定义位置
//
// param:
//   - source	定义位置
//
// return:
//   - 文件路径与行号，无法拆分时返回空
func splitSourceLine(source string) (string, int) {
	if source == "" || strings.HasPrefix(source, "<autogenerated>") {
		return "", 0
	}
	index := strings.LastIndex(source, ":")
	if index < 0 {
		return "", 0
	}
	line, err := strconv.Atoi(source[index+1:])
	if err != nil {
		return "", 0
	}
	return source[:index], line
}

// functionParamNames	在源文件中查找函数定义并提取参数名
// 先按函数名 + 行号匹配具名函数/方法声明，失败时按行号匹配函数字面量（匿名函数）
//
// param:
//   - file	源文件路径
//   - line	函数定义行号
//   - funcName	函数名，匿名函数传入 funcN 形式的运行时名称
//
// return:
//   - 参数名列表，未命名参数记为空字符串，未找到时返回 nil
func functionParamNames(file string, line int, funcName string) []string {
	fset := token.NewFileSet()
	parsed, err := parser.ParseFile(fset, file, nil, 0)
	if err != nil {
		return nil
	}

	// 具名函数/方法：按名称匹配，同名时以行号为准
	if funcName != "" {
		var matched *ast.FieldList
		for _, decl := range parsed.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Name.Name != funcName || fn.Type.Params == nil {
				continue
			}
			matched = fn.Type.Params
			if fset.Position(fn.Pos()).Line == line {
				break
			}
		}
		if matched != nil {
			return fieldListNames(matched)
		}
	}

	// 匿名函数：取包含目标行且起始行最接近（最内层）的函数字面量
	var lit *ast.FuncLit
	litLine := 0
	ast.Inspect(parsed, func(node ast.Node) bool {
		candidate, ok := node.(*ast.FuncLit)
		if !ok {
			return true
		}
		start := fset.Position(candidate.Pos()).Line
		end := fset.Position(candidate.End()).Line
		if start <= line && line <= end && start > litLine {
			lit, litLine = candidate, start
		}
		return true
	})
	if lit == nil {
		return nil
	}
	return fieldListNames(lit.Type.Params)
}

// fieldListNames	展开参数列表的参数名，支持 func(a, b int) 的分组声明
//
// param:
//   - fields	参数列表
//
// return:
//   - 参数名列表，未命名参数记为空字符串
func fieldListNames(fields *ast.FieldList) []string {
	if fields == nil {
		return nil
	}
	names := make([]string, 0, len(fields.List))
	for _, field := range fields.List {
		if len(field.Names) == 0 {
			names = append(names, "")
			continue
		}
		for _, name := range field.Names {
			names = append(names, name.Name)
		}
	}
	return names
}
